git remote add S1ckick                   https://github.com/S1ckick/spbetu_comparch_2020_9382.git            # Субботин
git remote add somewaytolive             https://github.com/somewaytolive/spbetu_comparch_2020_9382.git      # Круглова
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
#git remote add                           https://github.com//spbetu_comparch_2020_9382.git                  # 
